### ISSUE TITLE
Update all instances of Patient modification in commands

### ISSUE THREAD

**Issue by BlopApple** [AY2223S1-CS2103T-T12-4/tp#233]
The current method of creating a new immutable `Patient` after every command relating to it involves using the `Patient` constructor with a long list of attributes. A cleaner method to create a new immutable `Patient` can be used for ease of future implementations and code clarity.

**Comment by izzahaj** [comment]
I was thinking we could have 'setters' for each field in the `Patient` class (those that can't be edited using the edit patient feature), but instead of modifying patient attributes, they could behave similar to `TaskList#edit()`  (which returns a new `TaskList`) and return a new `Patient`.

So maybe we could have something like this in the `Patient` class:
```java
public Patient setConditions(ConditionList conditions) {
    return new Patient(getName(), getPhone(), getEmail(), getAddress(), conditions,
            getTasks(), getTags());
}
```
