### ISSUE TITLE
[PE-D][Tester D] Adding a patient task with invalid time for description turns out to be successful

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-4/tp#315]
When specifying the time as `2400` for a patient task in the `add` command, there is no error message thrown and the application outputs the time as `0000`. This might be confusing for the user as `2400` should not be a conventional time value in the 24-hour time format.

Example of bug (the command used to invoke the error is shown in the text box, accessed using the up arrow key):

![image.png](https://raw.githubusercontent.com/nseah21/ped/main/files/2128e88d-3f84-4e77-9775-e95fa9ab238f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nseah21/ped#5

**Comment by rama-pang** [comment]
In the tester's command, the date time is specified to `10-10-22 2400`, and UniNurse adds it as a task for `11-10-22 0000` (which makes sense, since `2400` is "the moment when the day (`10-10-22`) ends"; i.e., it's the beginning of the next day). So, functionality-wise, this is a non-issue.

Thoughts from others?
